# Generated by Django 5.2.5 on 2025-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('total_tickets', models.PositiveIntegerField()),
                ('tickets_remaining', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('image_url', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2hsa5aYA0NfcvhScC8i3nm4EO0G93eaolqA&s', max_length=500)),
            ],
        ),
    ]
