# Generated by Django 5.2.5 on 2025-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
