# Generated by Django 5.2.5 on 2025-08-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_image_url_event_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2hsa5aYA0NfcvhScC8i3nm4EO0G93eaolqA&s', max_length=500),
        ),
    ]
