# Generated by Django 5.2.5 on 2025-08-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_image_url_event_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
