version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: django-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        until nc -z db 3306; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  db_data:
